Pong-Beat-Makers/frontend

src/Login/login.css, src/Login/loginUtils.js, src/Modals/profileModalTemplate.js, src/Rank/rankTemplate.js, src/Rank/rankUtils.js, src/app.js
추가 / 변경 사항 :
1. 친구 추가 버튼 누르면 띄우는 프로필 검색 모달 추가
2. 프로필 검색 모달에서 검색창에 글자 입력 시 백엔드 유저 조회 api 호출해서 결과 띄움
앞으로 할 일 :
1. 프로필 검색 결과에서 특정 프로필 누를 시 상세정보 조회하는 로직
2. 그 외 유저관리 api 호출
=> add: profile search modal fetch

src/Game/SocketApp.js, src/Game/game-modal.css, src/Game/gameApp.js, src/Game/gameTemplate.js, src/Game/gameUtils.js, src/Profile/modalUtils.js
css 부분 조금 수정했습니다 !!
`GameApp`에서 관리하던 web socket 부분을 `SocketApp` 객체에 관리하도록 변경하였습니다.
이제 web socket 통신은 `SocketApp`에서 관리하고, `GameApp`은 받은 데이터를 렌더링해주는 객체입니다.
=> add Random Game

src/Login/player.js, src/app.js
=> export Player

src/Chat/chatSocketUtils.js, src/Login/loginUtils.js, src/Login/player.js
- 첫 로그인 시 온라인인 친구 목록으로 갱신
- 온오프라인 실시간 갱신
=> feat : 유저 온오프라인 확인 기능 추가

src/Profile/modalUtils.js
- save button event listener 틀만 구현 완료
=> feat : user profile 에서 nickname, status message 가져오기 구현

src/Chat/chatRoomUtils.js, src/Chat/chatSocketUtils.js, src/Login/loginUtils.js, src/Login/player.js, src/Public/global.js
1. 기존 chatToken으로 소통하던 부분 전부 nickname으로 변경했습니다. 
2. 세부 프로필 모달창에서 채팅 버튼 누르면 채팅창 뜨도록 수정했습니다. 
3. 기존 BACKEND 전역변수 하나로 되어있는 서버 도메인 USER랑 CHAT으로 포트번호 다르게 나누었습니다.
//
채팅부분 코드에서 fetch 사용한 부분 전부 async & await으로 수정하고자 합니다. 
랭킹 불러오는 부분 추가하겠습니다.
=> add: profile chat btn function, change server domains

src/Game/SocketApp.js, src/Public/global.js
=> !HOTFIX : 도메인 주소 에러 수정

src/Login/loginSuccessTemplate.js, src/Login/loginUtils.js, src/Public/components/profile-section.css
In case username includes "User", advice message "We advise you to change your nickname!" will be displayed above the Username in profile section.
=> advice message for common nickname users updated

src/Chat/chatRoomUtils.js, src/Game/SocketApp.js, src/Game/game-modal.css, src/Game/gameTemplate.js, src/Game/gameUtils.js, src/Login/loginSuccessTemplate.js, src/Login/loginUtils.js, src/Login/player.js, src/Profile/friend-modal.css, src/Profile/modalUtils.js, src/Public/components/profile-section.css, src/Rank/rankUtils.js
+ 기존 방식
먼저 HTML `Template에서 friendList `개수만큼 렌더링한 후 `querySeletorAll()`로 잡아서 다시 반복해 이벤트를 걸어주고 다른 처리를 해줍니다.
+ 바뀐점
` friendList.forEach()`로 안의 아이템으로 friendModalClick(nickname)호출 시 해당 모달을 띄워줍니다. 한 노드가 생성될 때마다 이벤트를 걸어줍니다.
=> REFACTOR: Friend Detail

src/Login/loginSuccessTemplate.js, src/Login/loginUtils.js, src/Login/player.js, src/Profile/modalUtils.js, src/Profile/profileModalTemplate.js
=> FIXED: nickname -> id

src/Chat/chat.css, src/Chat/chatPageUtils.js, src/Chat/chatSocketUtils.js, src/Chat/chatTemplate.js, src/Public/clickUtils.js, src/Rank/rankUtils.js, src/route.js
- changeUrl함수에 doPush 인자를 추가하여 popstate (뒤로 가기 / 앞으로 가기) 버튼 클릭 시에는 pushState를 하지 않도록 하였습니다. 
- 채팅방 밖에서 새로운 채팅을 받으면 브라우저 알림을 띄우는데, 처음 알림 수신 시 알림 허용 요청을 보냅니다. (시스템 설정에서 추가 알림 허용 설정이 필요합니다. 해당 부분은 Home 페이지 설명에 추가하면 좋을 것 같습니다.)
=> FIX: changeUrl, new chat alert

src/Chat/chat-modal.css, src/Chat/chat.css, src/Chat/chatApp.js, src/Chat/chatPageUtils.js, src/Chat/chatRoomUtils.js, src/Chat/chatSocketUtils.js, src/Chat/chatTemplate.js, src/Game/SocketApp.js, src/Game/gameApp.js, src/Game/gameUtils.js, src/Login/loginUtils.js, src/Login/player.js, src/Profile/modalUtils.js, src/Public/clickUtils.js, src/Public/components/profile-section.css, src/Rank/rankUtils.js, src/app.js
Chat socket 부분 nickname -> id 로 수정하다보니 리펙토링 진행했습니다 ... !!
기존에 있었던 코드량이 워낙 방대해 .. 완전하지 못한 코드인 것 같아요 !!! 최선을 다해 고쳐보았습니다.
현재 제가 작동해본 결과 눈으론 잘 돌아가서 올립니다.. rank 페이지 부분은 아직 못했습니다 !! 그 부분 user server에서도 수정이 필요할 듯 싶어요 !!
=> REFACTOR: chat socket

src/Chat/chat-modal.css, src/Chat/chatApp.js, src/Chat/chatRoomUtils.js, src/Profile/modalUtils.js
=> fix : 유저 실시간 on/offline 구현 수정 

src/Login/loginUtils.js, src/Login/player.js, src/Profile/modalUtils.js, src/route.js
/chat /rank 등의 페이지로 접근 시 해당 페이지로 이동할 수 있도록 라우팅 추가했습니다. 
chatApp을 player 내부에 넣었습니다.
=> add: Routing when first access

src/Chat/chat.css, src/Chat/chatSocketUtils.js, src/Chat/chatTemplate.js
=> FIX: chat alert from browser to custom

src/Chat/chatApp.js, src/Chat/chatPageUtils.js, src/Chat/chatRoomUtils.js, src/Chat/chatSocketUtils.js, src/Login/loginUtils.js, src/Profile/modalUtils.js, src/Rank/rankUtils.js
이제 채팅 모달을 띄우는 기준이 아닌 chatbox 생성 기준으로 업데이트합니다!
=> FIX: update chat room

src/Profile/modalUtils.js, src/Public/clickUtils.js, src/Rank/rankUtils.js, src/route.js
기존에는 인자로 chatApp.getApp()을 받았었는데, 내부에서 profile modal 띄울 때 chatApp 자체가 필요한 것으로 확인되어 해당 부분 수정하였습니다.
=> FIX: setRankPage 인자 수정

src/Chat/chatApp.js, src/Chat/chatPageUtils.js, src/Chat/chatSocketUtils.js, src/Profile/modalUtils.js
=> FIX: invite message

src/Chat/chat-modal.css, src/Chat/chatApp.js, src/Chat/chatPageUtils.js, src/Chat/chatRoomUtils.js, src/Chat/chatSocketUtils.js, src/Login/loginUtils.js
로드되고 나서 `settimeout()` 함수 한번 호출하는 ... 코드여서 처음 변수를 비웠습니다 !
나머지 최적화 진행하였습니다 ~~
=> FIX: twice load

src/Login/loginTemplate.js, src/Login/loginUtils.js
=> FIX TYPO: twoFATempate -> twoFATemplate

src/Chat/chatPageUtils.js, src/Chat/chatSocketUtils.js, src/Game/SocketApp.js, src/Game/gameApp.js, src/Game/gameUtils.js
invite btn disabled 되는 문제 해결했습니다 !
이제 토너먼트 게스트 전체 무조건 다른 아이콘으로 표시됩니다.
오타 수정했습니다 ~~!
=> FIX: invite btn disabled

src/Chat/chatPageUtils.js, src/Chat/chatRoomUtils.js, src/Profile/friend-modal.css, src/Profile/modalUtils.js
try 블록 안에 있어야할 코드가 바깥에 있는걸 발견했습니다 ..
=> FIX: fetch in try block

src/Game/SocketApp.js, src/Game/game-modal.css, src/Login/loginUtils.js, src/Profile/modalUtils.js, src/Profile/profile-modal.css, src/Profile/profileModalTemplate.js, src/Public/components/modal.css, src/Public/variables.css
=> FEAT: [edit user]block duplicate name

src/Chat/chatApp.js, src/Chat/chatPageUtils.js, src/Chat/chatSocketUtils.js, src/Game/SocketApp.js, src/Game/game-modal.css, src/Game/gameTemplate.js, src/Game/gameUtils.js
=> FEAT: tournament board modal

src/Chat/chat.css, src/Chat/chatApp.js, src/Game/SocketApp.js, src/Game/gameUtils.js, src/Public/components/modal.css
=> user can't play at in game

src/Game/SocketApp.js, src/Game/game-modal.css, src/Home/homeTemplate.js, src/Login/loginUtils.js, src/Profile/modalUtils.js
프로필 수정 모달에서 'User(숫자)' 이외의 값의 에러를 빨간색으로 나오게 통일시켰습니다.
인게임에서 c 버튼 (camera toggle) 제거하였습니다!
42tsc-Pong -> Pong-Beat-Makers 로 변경하였습니다!
=> FIX: edit profile & game button c

src/Chat/chatApp.js
You have successfully logged in!
=> You have successfully logged in!
